CREATE DATABASE IF NOT EXISTS BD_2026;
USE BD_2026;

-- Creacion de la tabla COTIZACION
CREATE TABLE IF NOT EXISTS COTIZACION (
    COD_COTI INT PRIMARY KEY,
    CLIENTE VARCHAR(100) NOT NULL,
    MERCANCIA VARCHAR(100) NOT NULL,
    VALOR_USD REAL NOT NULL,
    PESO REAL NOT NULL,
    TOTAL_SOLES REAL NOT NULL
);

-- Procedimientos almacenados CRUD
-- 1. Listar todas las cotizaciones
DROP PROCEDURE IF EXISTS SP_LISTAR_COTIZACIONES;
CREATE PROCEDURE SP_LISTAR_COTIZACIONES()
SELECT * FROM COTIZACION;

-- 2. Insertar una cotizacion
DROP PROCEDURE IF EXISTS SP_INSERTAR_COTIZACION;
CREATE PROCEDURE SP_INSERTAR_COTIZACION(
    CODI INT,
    NOM_CLI VARCHAR(100),
    NOM_MER VARCHAR(100),
    VALOR REAL,
    PESO REAL,
    TOTAL REAL
)
INSERT INTO COTIZACION VALUES(CODI, NOM_CLI, NOM_MER, VALOR, PESO, TOTAL);

-- 3. Eliminar una cotizacion por su codigo
DROP PROCEDURE IF EXISTS SP_ELIMINAR_COTIZACION;
CREATE PROCEDURE SP_ELIMINAR_COTIZACION(
    CODI INT
)
DELETE FROM COTIZACION WHERE COD_COTI = CODI;

-- 4. Editar una cotizacion
DROP PROCEDURE IF EXISTS SP_EDITAR_COTIZACION;
CREATE PROCEDURE SP_EDITAR_COTIZACION(
    CODI INT,
    NOM_CLI VARCHAR(100),
    NOM_MER VARCHAR(100),
    VALOR REAL,
    PESO REAL,
    TOTAL REAL
)
UPDATE COTIZACION 
SET CLIENTE = NOM_CLI, MERCANCIA = NOM_MER, VALOR_USD = VALOR, PESO = PESO, TOTAL_SOLES = TOTAL
WHERE COD_COTI = CODI;
